source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'bcrypt'
gem 'devise'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'font-awesome-rails'

gem 'faker'

gem 'bootstrap-sass'

gem 'flat-ui-sass', github: 'wingrunr21/flat-ui-sass'

# ActiveAdmin for backend maintenance of database entries
gem 'activeadmin', github: 'activeadmin'
#gem 'actionpack'
#gem 'railties'

#Databases on Rails. Build a persistent domain model by mapping database tables to Ruby classes. Strong conventions for associations, validations, aggregations, migrations, and testing come baked-in
#gem 'activerecord'

#Get countries list and Converts name to code
gem 'country_select', github: 'stefanpenner/country_select'

#Importing csv file into ActiveAdmin tables
gem "active_admin_import" , github: "activeadmin-plugins/active_admin_import"
# gem 'activerecord-import'

#Authorization Gem for Ruby on Rails
gem "pundit"

gem 'wicked'

group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
  
  group :development do 
  	gem "letter_opener"
  end
  
  group :production do 
    gem 'rails_12factor'
  end

